name: Local
variables:
  - secret: true
    name: baseUrl
  - secret: true
    name: token
  - secret: true
    name: refresh_token
  - secret: true
    name: project_pk
  - secret: true
    name: stage_id
  - secret: true
    name: participant_id
  - secret: true
    name: expense_id
  - secret: true
    name: incident_id
  - secret: true
    name: report_id
  - secret: true
    name: supplier_id
